### ISSUE TITLE
Understanding /validate_attribute_info

### ISSUE THREAD

**Issue by jordibuj** [DECODEproject/dddc-credential-issuer#10]
The endpoint /validateAttributeInfo is returning a 412 error when I expect a 200. 
Use case is as follows:
First I create an AuthorizableAttribute by calling POST /authorizable_attribute with:
```
{
  "authorizable_attribute_id": "residencyInBarcelona",
  "authorizable_attribute_info": [
    {"dni": "string"}, {"censusPostalCode": "string"}
  ]
}
```
Then I call POST /validate_attribute_info with:
```
{
  "authorizable_attribute_id": "residencyInBarcelona",
  "values": [
    {"dni": "111222333D"}, {"censusPostalCode": "08002"}
  ]
}
```
This returns the error.
I was expecting ok but it only returns ok if I put "string" as the value for both fields.
Is my understanding correct?

**Comment by uladribia** [comment]
No, its is not well understood. What you need to pass is the SET of accepted values.
LIke,

`
{
  "authorizable_attribute_id": "residencyInBarcelona",
  "authorizable_attribute_info": [
    {"dni": ["111222333D","dni2",23}, {"censusPostalCode": "08002",08012}
  ]
}
`
Then, if you do this for instance:
`
{
  "authorizable_attribute_id": "residencyInBarcelona",
  "values": [
    {"dni": "111222333D"}, {"censusPostalCode": 08012}
  ]
}
`
It will work, as the credential issuer checks that whatever value is passed is in the DEFINED SET.
In your case, if you pass "string", since "string" is on the set, it returns ok.

**Comment by uladribia** [comment]
Maybe the docs should be clarified on this point.

**Comment by jordibuj** [comment]
Ah, ok, but in [the requirements](https://github.com/DECODEproject/dddc-credential-issuer/blob/master/REQUIREMENTS.md) it says the attribute_info is a pair (attribute_key, attribute_type), so it should perhaps say something like (attribute_key, array_of_valid_attribute_values)?

**Comment by puria** [comment]
Will look into it later today, and update you, and also clarify better on documentation ;)

**Comment by uladribia** [comment]
The API was written after the requirements where.. and things changed in between. Can you test the code snippet I passed and make sure what I say is correct? I do believe it's like that.

**Comment by uladribia** [comment]
I took a look at the code again, and the following function in https://github.com/DECODEproject/dddc-credential-issuer/blob/master/app/main.py should return a unique_id generated with the hash function, not TRUE, in order to start the COCONUT flow as described in the requirements, I do believe...

```python
@api.post("/validate_attribute_info")
def validate_attribute_info(item: ValidateAuthorizableAttributeInfoInput):
    authorizable_attribute_id = item.authorizable_attribute_id
    values = set([(k, v) for _ in item.values for k, v in _.items()])
    aa = AuthorizableAttribute.by_aa_id(authorizable_attribute_id)

    if not values <= aa.value_set:
        raise HTTPException(
            status_code=HTTP_412_PRECONDITION_FAILED,
            detail="Values mismatch not in Authorizable Attribute",
        )

return True
```
In any case, it should return a valid HTTP value, not a simple True. Right?

**Comment by puria** [comment]
As the behaviour completely changed, will close this issue, the new API is also renamed /credential, take a look at that.
